### ISSUE TITLE
df_interact.ahk Syntax Issue/Typo

### ISSUE THREAD

**Issue by Barrow** [joelpt/quickfort#3]
Line 125 of the df_interact.ahk sourcecode reads:
Send, %keys%
rather than
Send, %key%

**Comment by joelpt** [comment]
Nice catch.

Did you find if changing it to %key% remedied the crazy key-mode playback behavior you were seeing in https://www.youtube.com/watch?v=vHx1VGdkFyM?

**Comment by Barrow** [comment]
It didn't; I'm not at a computer at the moment, but will give more details
when I am.
On Jun 19, 2012 1:31 PM, "Joel Thornton" <
reply@reply.github.com>
wrote:

**Comment by joelpt** [comment]
Made this fix; fixed code is pushed to repo.
